version: '3.9'

services:
    dev-db-pg:
        image: postgres
        restart: always
        container_name: dev-db-pg
        ports:
            - 5435:5432
        environment:
            POSTGRES_USERNAME: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres

volumes:
    postgres:
