name: Playwright Test
on:
    push:
        branches:
            - main

jobs:
    playwright-test:
        env:
            TEST_PASSWORD: 'test'
            CLIENT_URL: 'https://project-showcase-staging.vercel.app/'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test
