name: Playwright Tests w/ Postgres

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: adambirds/docker-compose-action@v1.3.0
              with:
                  compose-file: 'ci-compose.yml'
            - name: Build and start containers
              run: docker-compose -f ci-compose.yml up
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run NextJS (preinstalled)
              run: docker-compose exec nextjs npm run start
            - name: Run tests
              run: docker-compose exec nextjs npm run e2e:test
            - name: Stop containers
              run: docker-compose down
